name: Test Approve

on:
    workflow_dispatch:
    pull_request:
         types: [ opened, reopened, synchronize ]

jobs:
    test:
        name: Test Approve
        runs-on: ubuntu-latest
        steps:
            - name: Generate Token
              id: generate-token
              uses: atolycs/create-app-auth@v1
              with:
                app-id: ${{ secrets.APP_ID }}
                private-key: ${{ secrets.APP_PEM }}

            - name: checkout
              uses: actions/checkout@v4

            - name: Disapprove
              uses: atolycs/disapprove-action@main
              if: github.event.action == 'reopened'
              with:
                token: ${{ steps.generate-token.outputs.token }}
                message: "Disapproved"

            - name: Build test
              run: |
                echo "building..."

            - name: Running Test
              run: |
                echo "Running..."

            - name: Approve Test
              uses: ./
              with:
                token: ${{ steps.generate-token.outputs.token }}
                message: "Approved! meow." 